version: '3.7'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: healthcare
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - healthcare-network

  patient-service:
    build:
      context: ./patient
      dockerfile: Dockerfile
    container_name: patient-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/patient_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - healthcare-network

  doctor-service:
    build:
      context: ./doctor
      dockerfile: Dockerfile
    container_name: doctor-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/doctor_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    networks:
      - healthcare-network

networks:
  healthcare-network:
    driver: bridge

volumes:
  mysql-data:
